<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-Q0GEFUM" failures="2" tests="10" name="free crm loginPageTest chrome_90" time="4.287" errors="0" timestamp="2022-07-23T16:23:50 IST">
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyDoLoginTest" time="0.66"/>
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyLoginPageTilesTest" time="0.173">
    <skipped/>
  </testcase> <!-- verifyLoginPageTilesTest -->
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyLoginPageTilesTest" time="0.099">
    <skipped/>
  </testcase> <!-- verifyLoginPageTilesTest -->
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyLoginPageTilesTest" time="0.094">
    <skipped/>
  </testcase> <!-- verifyLoginPageTilesTest -->
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyLoginPageTilesTest" time="0.094">
    <failure type="java.lang.AssertionError" message="Lists differ at element [0]: Login != My Account expected [Login] but found [My Account]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [0]: Login != My Account expected [Login] but found [My Account]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:1103)
at org.testng.Assert.assertEquals(Assert.java:1065)
at com.qa.freecrm.tests.LoginPageTest.verifyLoginPageTilesTest(LoginPageTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyLoginPageTilesTest -->
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyLoginPageTitleTest" time="0.0">
    <skipped/>
  </testcase> <!-- verifyLoginPageTitleTest -->
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyLoginPageTitleTest" time="0.0">
    <skipped/>
  </testcase> <!-- verifyLoginPageTitleTest -->
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyLoginPageTitleTest" time="0.0">
    <skipped/>
  </testcase> <!-- verifyLoginPageTitleTest -->
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyLoginPageTitleTest" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [Account Login] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [Account Login] but found [My Account]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.freecrm.tests.LoginPageTest.verifyLoginPageTitleTest(LoginPageTest.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyLoginPageTitleTest -->
  <testcase classname="com.qa.freecrm.tests.LoginPageTest" name="verifyisForgotPasswordLinkTest" time="0.016"/>
</testsuite> <!-- free crm loginPageTest chrome_90 -->
